plugins:
  - remark-mdx
  - remark-math
  - remark-frontmatter
  - remark-gfm
  - remark-preset-lint-consistent
  - remark-preset-lint-recommended
  - remark-preset-lint-markdown-style-guide
  - [remark-lint-file-extension, "mdx"]
  - [remark-lint-emphasis-marker, "_"]
  - [remark-lint-list-item-indent, "one"]
  - [remark-lint-list-item-spacing, false]
  - [remark-lint-link-title-style, "'"]
  # - remark-preset-prettier
